# Use the official PostgreSQL image from Docker Hub
FROM postgres:13

# Define environment variables for username and password
ENV POSTGRES_USER postgres
ENV POSTGRES_PASSWORD test

# Set the default database to initialize when starting the container
ENV POSTGRES_DB mydatabase

# Expose the PostgreSQL port
EXPOSE 5432